name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      #      - name: setup jdk 8.0
      #        uses: actions/setup-java@v2
      #        with:
      #          distribution: adopt
      #          java-version: 8.0
      #      - name: make gradle wrapper executable
      #        run: chmod +x ./gradlew
      #      - name: build
      #        run: ./gradlew build
      #      - name: publish
      #        env:
      #          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      #          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      #        run: ./gradlew publish -Pbuild=$GITHUB_RUN_NUMBER -Puser=$NEXUS_USERNAME -Ppassword=$NEXUS_PASSWORD
      - name: create release
        uses: actions/create-release@v1
        env:
          A: $GITHUB_RUN_NUMBER
          B: ${{ env.GITHUB_RUN_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 6.0.0
          release_name: Release ${{ secrets.NEXUS_USERNAME }}
          draft: true
#      - name: release
#        uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: 6.0.0-$GITHUB_RUN_NUMBER
#          release_name: Release 6.0.0-$GITHUB_RUN_NUMBER
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/